name: deployment

on:
  pull_request:
    
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout code 
      - uses: actions/setup-node@v3
        name: npm setup
        with:
          entrypoint: backend
          node-version: 16
      - name: npm-init
        run: cd backend && npm install
      - name: start backend
        run: cd backend && npm start && sleep 10 &
      - uses: grossamos/rudra@v0.1.3
        name: init rudra
        with:
          stage: "preperation"
          openapi-source: "backend/openapi.yaml"
          instance-url: "http://localhost:3000"
          port: 3001
          debug: true
          test-coverage: "50%"
      - name: debug hell
        run: curl --location --request POST 'http://localhost:3001/api/users/' --header 'Content-Type: application/json' --data-raw '{"email":"admin@gotcaked.eu","name": "LeLItsMeAdmin","description": "I AM THE ADMIN","password":"TWFfr4cITdKgXAh1.aA"}'
      - uses: matt-ball/newman-action@master
        name: run integration tests
        with:
          collection: backend/tests/newman/gotCaked.postman_collection.json
          environment: backend/tests/newman/ci.postman_environment.json
      - uses: grossamos/rudra@v0.1.3
        name: eval rudra
        if: always()
        with:
          stage: "evaluation"
