name: deployment

on:
  pull_request:
    
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout code 
      - uses: actions/setup-node@v3
        name: npm setup
        with:
          entrypoint: backend
          node-version: 16
      - name: npm-init
        run: cd backend && npm install
      - name: start backend
        run: cd backend && npm start && sleep 10 &
      - uses: grossamos/rudra@v0.1.3
        name: init rudra
        with:
          stage: "preperation"
          openapi-source: "backend/openapi.yaml"
          instance-url: "http://localhost:3000"
          port: 3001
          test-coverage: "50%"
      - uses: matt-ball/newman-action@master
        name: run integration tests
        with:
          collection: backend/tests/newman/gotCaked.postman_collection.json
          environment: backend/tests/newman/ci.postman_environment.json
      - name: tests
        run: cd backend/tests/newman && ./run_test.sh local
      - uses: grossamos/rudra@v0.1.3
        name: eval rudra
        with:
          stage: "evaluation"
